parser: babel-eslint

extends:
  - 'eslint:recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:react/recommended'

env:
  node: true
  browser: true

settings:
  import/order: 'eslint-plugin-import'


rules:
  import/no-unresolved: 0
  import/extensions: 0
  no-console: 0
  react/prop-types: 0
  react/display-name: 0
